const Joi = require('joi');

    
const Joi = require('joi');

const authorizationApprovedSchema= Joi.object({
  userId: Joi.number().integer().required(),
  categoryId: Joi.number().integer().required(),
  subcategoryId: Joi.number().integer().required(),
  classificationId: Joi.number().integer().required(),
  feeId: Joi.number().integer().required(),
  date_received: Joi.date().optional(),
  form_number: Joi.string().optional(),
  boiler_pressure_classification: Joi.string().valid(
    "Class I", "Class II", "Class III", "Class IV", "Class V"
  ).optional(),
  lifting_equipment_classification: Joi.string().valid(
    "Class VI", "Class VII", "Class VIII", "Class IX", "Class X"
  ).optional(),
  type_of_service: Joi.string().valid("New Application", "Re-Application").required(),
  application_type: Joi.string().valid("New Application", "Re-Application").required(),
  available_for_documentation_review: Joi.boolean().optional(),
  exemption_request: Joi.boolean().optional(),
  company_name: Joi.string().optional(),
  cac_registration_number: Joi.string().optional(),
  physical_address: Joi.string().optional(),
  year_of_commencing_business: Joi.string().optional(),
  number_of_employee: Joi.number().integer().optional(),
  member_nagobin: Joi.string().optional(),
  member_leia: Joi.string().optional(),
  member_indt: Joi.string().optional(),
  member_other_bodies: Joi.string().optional(),
  quality_certification: Joi.string().optional(),
  competence_category: Joi.string().optional(),
  competence_line: Joi.string().optional(),
  incidental_line: Joi.string().optional(),
  contact_person: Joi.string().optional(),
  telephone: Joi.string().optional(),
  email_address: Joi.string().email().optional(),
  technical_supervisor_name: Joi.string().optional(),
  technical_supervisor_address: Joi.string().optional(),
  technical_supervisor_email: Joi.string().email().optional(),
  technical_supervisor_date_of_birth: Joi.date().optional(),
  technical_supervisor_phonenumber: Joi.string().optional(),
  supervisor_high_school: Joi.object().optional(),
  supervisor_polytechnic: Joi.object().optional(),
  supervisor_university: Joi.object().optional(),
  supervisor_professional_qualification_institution: Joi.string().optional(),
  supervisor_date_of_issue: Joi.date().optional(),
  supervisor_professional_expiration_date: Joi.date().optional(),
  supervisor_experience_name_of_company: Joi.string().optional(),
  supervisor_joining_date: Joi.string().optional(),
  supervisor_exit_date: Joi.string().optional(),
  approved_inspector_name: Joi.string().optional(),
  approved_inspector_address: Joi.string().optional(),
  approved_inspector_email: Joi.string().email().optional(),
  approved_inspector_date_of_birth: Joi.date().optional(),
  approved_inspector_phonenumber: Joi.string().optional(),
  inspector_high_school: Joi.object().optional(),
  inspector_polytechnic: Joi.object().optional(),
  inspector_university: Joi.object().optional(),
  inspector_professional_qualification_institution: Joi.string().optional(),
  inspector_date_of_issue: Joi.date().optional(),
  inspector_professional_expiration_date: Joi.date().optional(),
  inspector_experience_name_of_company: Joi.string().optional(),
  inspector_joining_date: Joi.string().optional(),
  inspector_exit_date: Joi.string().optional(),
  company_declaration_date: Joi.date().optional(),
  company_responsible_charge: Joi.string().optional(),
  companyQualityManual: Joi.string().optional(),
  operationalProcedures: Joi.string().optional(),
  companyDocumentation: Joi.string().optional(),
  documentationQuality: Joi.string().optional(),
  designerDocumentation: Joi.string().optional(),
  weldingDocumentation: Joi.string().optional(),
  ndtDocumentation: Joi.string().optional(),
  indtDocumentation: Joi.string().optional(),
  isoCertification: Joi.string().optional(),
  is_draft: Joi.boolean().optional(),
});




const competencyCertificationFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    form_type: Joi.string().allow(null),
    technical_authority: Joi.boolean().allow(null),
    appointed_person: Joi.boolean().allow(null),
    approved_person: Joi.boolean().allow(null),
    classA: Joi.boolean().allow(null),
    classB: Joi.boolean().allow(null),
    classC: Joi.boolean().allow(null),
    classD: Joi.boolean().allow(null),
    classE: Joi.boolean().allow(null),
    new_application: Joi.boolean().allow(null),
    re_application: Joi.boolean().allow(null),
    training_start_date: Joi.date().allow(null),
    training_completion_date: Joi.date().allow(null),
    documentation_available_for_review: Joi.boolean().allow(null),
    exemption_requested: Joi.boolean().allow(null),
    employer_name: Joi.string().allow(null),
    employer_physical_address: Joi.string().allow(null),
    employer_authorization_number: Joi.string().allow(null),
    employer_contact_person: Joi.string().allow(null),
    employer_contact_telephone: Joi.string().allow(null),
    employer_contact_email_address: Joi.string().email().allow(null),
    employer_quality_certifications: Joi.array().items(Joi.string()).allow(null),
    training_organization_name: Joi.string().allow(null),
    training_method: Joi.string().allow(null),
    training_organization_approval_number: Joi.string().allow(null),
    training_facility_location: Joi.string().allow(null),
    training_organization_quality_certifications: Joi.array().items(Joi.string()).allow(null),
    training_organization_contact_person: Joi.string().allow(null),
    training_organization_telephone: Joi.string().allow(null),
    training_organization_email: Joi.string().email().allow(null),
    applicant_name: Joi.string().allow(null),
    applicant_address: Joi.string().allow(null),
    applicant_date_of_birth: Joi.date().allow(null),
    applicant_email_address: Joi.string().email().allow(null),
    applicant_telephone_number: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line_number: Joi.string().allow(null),
    incidental_line_number: Joi.string().allow(null),
    high_school: Joi.object().allow(null),
    polytechnic: Joi.object().allow(null),
    university: Joi.object().allow(null),
    professional_qualification: Joi.object().allow(null),
    experience: Joi.object().allow(null),
    applicant_declaration_name: Joi.string().allow(null),
    applicant_declaration_date: Joi.date().allow(null),
    employer_responsible_charge_name: Joi.string().allow(null),
    employer_responsible_charge_date: Joi.date().allow(null),
    is_draft: Joi.boolean().default(false),
});

const trainingOrganizationFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    authorized_inspector: Joi.boolean().allow(null),
    design_engineer: Joi.boolean().allow(null),
    power_engineer: Joi.boolean().allow(null),
    welding_engineer: Joi.boolean().allow(null),
    refrigerator_engineer: Joi.boolean().allow(null),
    boiler_and_pressure_vessel_operator: Joi.boolean().allow(null),
    pressure_welder: Joi.boolean().allow(null),
    refrigeration_technician: Joi.boolean().allow(null),
    approved_person: Joi.boolean().allow(null),
    lift_technician: Joi.boolean().allow(null),
    crane_operator: Joi.boolean().allow(null),
    forklift_operator: Joi.boolean().allow(null),
    work_equipment_operator: Joi.boolean().allow(null),
    rigger: Joi.boolean().allow(null),
    scaffolding_technician: Joi.boolean().allow(null),
    abseiling_technician: Joi.boolean().allow(null),
    new_application: Joi.boolean().allow(null),
    re_application: Joi.boolean().allow(null),
    available_for_documentation_review: Joi.boolean().allow(null),
    exemption_request: Joi.boolean().allow(null),
    company_name: Joi.string().allow(null),
    physical_address: Joi.string().allow(null),
    year_of_commencing_business: Joi.string().allow(null),
    number_of_employee: Joi.number().integer().allow(null),
    member_nagobin: Joi.boolean().allow(null),
    member_leia: Joi.boolean().allow(null),
    member_indt: Joi.boolean().allow(null),
    member_other_bodies: Joi.string().allow(null),
    quality_certification: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line: Joi.string().allow(null),
    incidental_line: Joi.string().allow(null),
    contact_person: Joi.string().allow(null),
    telephone: Joi.string().allow(null),
    email_address: Joi.string().email().allow(null),
    technical_supervisor_name: Joi.string().allow(null),
    technical_supervisor_address: Joi.string().allow(null),
    technical_supervisor_email: Joi.string().email().allow(null),
    technical_supervisor_date_of_birth: Joi.date().allow(null),
    technical_supervisor_phonenumber: Joi.string().allow(null),
    high_school: Joi.object().allow(null),
    polytechnic: Joi.object().allow(null),
    university: Joi.object().allow(null),
    professional_qualification: Joi.object().allow(null),
    professional_qualification_institution: Joi.object().allow(null),
    experience: Joi.object().allow(null),
    name_of_user: Joi.string().allow(null),
    company_responsible_charge: Joi.string().allow(null),
    date_sign: Joi.date().allow(null),
    approval_category: Joi.string().allow(null),
    approval_class: Joi.string().allow(null),
    training_approval_number_ngtan: Joi.string().allow(null),
    director_of_factories: Joi.string().allow(null),
    date_sign_director_of_factories: Joi.date().allow(null),
    documents_uploaded: Joi.array().items(Joi.string()).allow(null),
    is_draft: Joi.boolean().default(false),
});

const renewalFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    form_number: Joi.string().allow(null),
    form_type: Joi.string().allow(null),
    equipment_registration: Joi.boolean().allow(null),
    certificate_of_competence: Joi.boolean().allow(null),
    certificate_of_authorization: Joi.boolean().allow(null),
    documentation_available: Joi.boolean().allow(null),
    exemption_requested: Joi.boolean().allow(null),
    company_name: Joi.string().allow(null),
    company_address: Joi.string().allow(null),
    company_cac_registration_number: Joi.string().allow(null),
    year_of_commencement: Joi.string().allow(null),
    number_of_employees: Joi.number().integer().allow(null),
    nagobin_membership: Joi.boolean().allow(null),
    leia_membership: Joi.boolean().allow(null),
    other_memberships: Joi.array().items(Joi.string()).allow(null),
    quality_certifications: Joi.array().items(Joi.string()).allow(null),
    previous_authorization_certificate_number: Joi.string().allow(null),
    previous_authorization_date_of_issue: Joi.date().allow(null),
    previous_authorization_expiry_date: Joi.date().allow(null),
    renewal_reason: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line_number: Joi.string().allow(null),
    incidental_line_number: Joi.string().allow(null),
    contact_person_name: Joi.string().allow(null),
    contact_person_email: Joi.string().email().allow(null),
    contact_person_phone: Joi.string().allow(null),
    responsible_charge_name: Joi.string().allow(null),
    declaration_date: Joi.date().allow(null),
    approval_category: Joi.string().allow(null),
    approval_class: Joi.string().allow(null),
    contractor_number: Joi.string().allow(null),
    director_of_factories: Joi.string().allow(null),
    director_signature_date: Joi.date().allow(null),
    uploaded_documents: Joi.array().items(Joi.string()).allow(null),
    is_draft: Joi.boolean().default(false),
});



const competencyCertificationFormLiftOperatorSchema = Joi.object({
    user_id: Joi.number().integer().required(),
    categoryId: Joi.number().integer(),
    subcategoryId: Joi.number().integer(),
    classificationId: Joi.number().integer(),
    incidentalClassificationId: Joi.number().integer(),
    feeId: Joi.number().integer().required(),
    paymentStatus: Joi.string().valid('unpaid', 'paid'),
    appStatus: Joi.string().valid('pending', 'approved', 'rejected', 'suspended'),
	type_of_certification: Joi.string().valid("Technical Authority", "Appointed Person", "Approved Person"),
    category_of_certification: Joi.string().valid(
        "Class A",
        "Class B",
        "Class C",
        "Class D",
        "Class E",
        "Class F",
        "Class G"
    ),
    application_type: Joi.string().valid("New Application", "Re-application"),
    available_for_documentation_review: Joi.boolean().allow(null),
    exemption_request: Joi.boolean().allow(null),
    employer_name: Joi.string(),
    employer_physical_address: Joi.string(),
    employer_authorization_number: Joi.string(),
    employer_quality_certifications: Joi.string(),
    employer_contact_person: Joi.string(),
    employer_contact_telephone: Joi.string(),
    employer_contact_email_address: Joi.string(),
    training_organization_name: Joi.string(),
    training_method: Joi.string().valid("Online", "Class Room", "Field"),
    training_organization_registration_number: Joi.string(),
    training_facility_location: Joi.string(),
    training_organization_quality_certifications: Joi.string(),
    training_organization_contact_person: Joi.string(),
    training_organization_telephone: Joi.string(),
    training_organization_email: Joi.string(),
    applicant_name: Joi.string(),
    applicant_address: Joi.string(),
    applicant_date_of_birth: Joi.date(),
    applicant_email_address: Joi.string(),
    applicant_telephone_number: Joi.string(),
    competence_category: Joi.string().allow(null),
    competence_line: Joi.string().allow(null),
    incidental_line: Joi.string().allow(null),
    High_school: Joi.object().allow(null),
    polytechnic: Joi.object().allow(null),
    university: Joi.object().allow(null),
    professional_qualification_institution: Joi.string().allow(null),
    date_of_issue: Joi.date().allow(null),
    professional_expiration_date: Joi.date().allow(null),
    experience_name_of_company: Joi.string().allow(null),
    company_declaration_date: Joi.date().allow(null),
    company_responsible_charge: Joi.string().allow(null),
    joining_date: Joi.string().allow(null),
    exit_date: Joi.date().allow(null),
    applicant_cv: Joi.string().allow(true),
    higher_education_certificate: Joi.string().allow(true),
    leia_experience: Joi.string().allow(true),
    training_certificate: Joi.string().allow(true),
    other_certificate: Joi.string().allow(true),
    employement_letter: Joi.string().allow(true),
    is_draft: Joi.boolean().default(false),
    createdAt: Joi.date(),
    updatedAt: Joi.date(),
});


module.exports = {
    authorizationApprovedSchema,
    competencyCertificationFormSchema,
    trainingOrganizationFormSchema,
    renewalFormSchema,
    competencyCertificationFormLiftOperatorSchema
};