const Joi = require('joi');

const authorizationApprovedSchema = Joi.object({
    categoryId: Joi.number().integer().allow(null),
    subcategoryId: Joi.number().integer().allow(null),
    classificationId: Joi.number().integer().allow(null),
    incidentalClassificationId: Joi.number().integer().allow(null),
    paymentStatus: Joi.string().valid('paid', 'unpaid').default('unpaid'),
    appStatus: Joi.string().valid('pending', 'approved', 'rejected').default('pending'),
    boilerServiceClassification: Joi.string().allow(null),
    typeOfService: Joi.string().allow(null),
    liftingServiceClassification: Joi.string().allow(null),
    applicationType: Joi.string().allow(null),
    certificationReview: Joi.boolean().default(false),
    exemption: Joi.boolean().default(false),
    companyName: Joi.string().allow(null),
    companyAddress: Joi.string().allow(null),
    companyCAC: Joi.string().allow(null),
    companyYear: Joi.number().allow(null),
    companyEmployee: Joi.number().allow(null),
    companyMembership: Joi.string().allow(null),
    companyQuality: Joi.string().allow(null),
    companyCompetence: Joi.string().allow(null),
    companyCompetenceLine: Joi.string().allow(null),
    companyIncidentalLine: Joi.string().allow(null),
    companyContactPerson: Joi.string().allow(null),
    companyTelephone: Joi.string().allow(null),
    companyEmail: Joi.string().email().allow(null),
    nagobinDocument: Joi.string().default(false),
    companyMembershipLeia: Joi.boolean().default(false),
    leiaDocument: Joi.string().allow(null),
    managerName: Joi.string().allow(null),
    managerAddress: Joi.string().allow(null),
    managerDOB: Joi.date().allow(null),
    managerEmail: Joi.string().email().allow(null),
    managerTelephone: Joi.string().allow(null),
    nameSchool: Joi.string().allow(null),
    dateAdmitted: Joi.date().allow(null),
    dateCompleted: Joi.date().allow(null),
    qualification: Joi.string().allow(null),
    institution: Joi.string().allow(null),
    dateIssue: Joi.date().allow(null),
    expirationDate: Joi.date().allow(null),
    nameCompany: Joi.string().allow(null),
    joinDate: Joi.date().allow(null),
    existDate: Joi.date().allow(null),
    inspectorName: Joi.string().allow(null),
    inspectorAddress: Joi.string().allow(null),
    inspectorDOB: Joi.date().allow(null),
    inspectorEmail: Joi.string().email().allow(null),
    inspectorTelephone: Joi.string().allow(null),
    professionalInstitution: Joi.string().allow(null),
    professionalDOI: Joi.date().allow(null),
    professionalExpireDate: Joi.date().allow(null),
    experienceCompanyName: Joi.string().allow(null),
    experienceJoinDate: Joi.date().allow(null),
    experienceExistDate: Joi.date().allow(null),
    companyResponsibleCharge: Joi.string().allow(null),
    companyResponsibleChargeDate: Joi.date().allow(null),
    companyQualityManuel: Joi.string().allow(null),
    operationalProcedures: Joi.string().allow(null),
    companyDocumentation: Joi.string().allow(null),
    documentationSupervisor: Joi.string().allow(null),
    isoCertification: Joi.string().allow(null),
    feeId: Joi.number().integer().allow(null),
    status: Joi.string().valid('pending', 'approved', 'rejected').default('pending'),
});

const authorizationManufacturerSchema = Joi.object({
    categoryId: Joi.number().integer().allow(null),
    subcategoryId: Joi.number().integer().allow(null),
    classificationId: Joi.number().integer().allow(null),
    incidentalClassificationId: Joi.number().integer().allow(null),
    paymentStatus: Joi.string().valid('paid', 'unpaid').default('unpaid'),
    appStatus: Joi.string().valid('pending', 'approved', 'rejected').default('pending'),
    boilerServiceClassification: Joi.string().allow(null),
    typeService: Joi.string().allow(null),
    liftingServiceClassification: Joi.string().allow(null),
    applicationType: Joi.string().allow(null),
    certificationReview: Joi.boolean().default(false),
    exemption: Joi.boolean().default(false),
    companyName: Joi.string().allow(null),
    companyAddress: Joi.string().allow(null),
    companyCac: Joi.string().allow(null),
    companyYear: Joi.number().allow(null),
    companyEmployee: Joi.number().allow(null),
    companyMembership: Joi.string().allow(null),
    companyQuality: Joi.string().allow(null),
    companyCompetence: Joi.string().allow(null),
    companyCompetenceLine: Joi.string().allow(null),
    companyIncidentalLine: Joi.string().allow(null),
    companyContactPerson: Joi.string().allow(null),
    companyTelephone: Joi.string().allow(null),
    companyEmail: Joi.string().email().allow(null),
    companyMembershipNagobin: Joi.boolean().default(false),
    companyMembershipLeia: Joi.boolean().default(false),
    managerName: Joi.string().allow(null),
    managerAddress: Joi.string().allow(null),
    managerDob: Joi.date().allow(null),
    managerEmail: Joi.string().email().allow(null),
    managerTelephone: Joi.string().allow(null),
    nameSchool: Joi.string().allow(null),
    dateAdmitted: Joi.date().allow(null),
    dateCompleted: Joi.date().allow(null),
    qualification: Joi.string().allow(null),
    institution: Joi.string().allow(null),
    dateIssue: Joi.date().allow(null),
    expirationDate: Joi.date().allow(null),
    nameCompany: Joi.string().allow(null),
    joinDate: Joi.date().allow(null),
    existDate: Joi.date().allow(null),
    inspectorName: Joi.string().allow(null),
    inspectorAddress: Joi.string().allow(null),
    inspectorDob: Joi.date().allow(null),
    inspectorEmail: Joi.string().email().allow(null),
    inspectorTelephone: Joi.string().allow(null),
    professionalInstitution: Joi.string().allow(null),
    professionalDoi: Joi.date().allow(null),
    professionalExpireDate: Joi.date().allow(null),
    experienceCompanyName: Joi.string().allow(null),
    experienceJoinDate: Joi.date().allow(null),
    experienceExistDate: Joi.date().allow(null),
    companyResponsibleCharge: Joi.string().allow(null),
    companyResponsibleChargeDate: Joi.date().allow(null),
    companyQualityManual: Joi.string().allow(null),
    operationalProcedures: Joi.string().allow(null),
    companyDocumentation: Joi.string().allow(null),
    documentationQuality: Joi.string().allow(null),
    designerDocumentation: Joi.string().allow(null),
    weldingDocumentation: Joi.string().allow(null),
    ndtDocumentation: Joi.string().allow(null),
    indtDocumentation: Joi.string().allow(null),
    isoCertification: Joi.string().allow(null),
    feeId: Joi.number().integer().allow(null),
    status: Joi.string().valid('pending', 'approved', 'rejected').default('pending'),
});

const competencyCertificationFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    form_type: Joi.string().allow(null),
    technical_authority: Joi.boolean().allow(null),
    appointed_person: Joi.boolean().allow(null),
    approved_person: Joi.boolean().allow(null),
    classA: Joi.boolean().allow(null),
    classB: Joi.boolean().allow(null),
    classC: Joi.boolean().allow(null),
    classD: Joi.boolean().allow(null),
    classE: Joi.boolean().allow(null),
    new_application: Joi.boolean().allow(null),
    re_application: Joi.boolean().allow(null),
    training_start_date: Joi.date().allow(null),
    training_completion_date: Joi.date().allow(null),
    documentation_available_for_review: Joi.boolean().allow(null),
    exemption_requested: Joi.boolean().allow(null),
    employer_name: Joi.string().allow(null),
    employer_physical_address: Joi.string().allow(null),
    employer_authorization_number: Joi.string().allow(null),
    employer_contact_person: Joi.string().allow(null),
    employer_contact_telephone: Joi.string().allow(null),
    employer_contact_email_address: Joi.string().email().allow(null),
    employer_quality_certifications: Joi.array().items(Joi.string()).allow(null),
    training_organization_name: Joi.string().allow(null),
    training_method: Joi.string().allow(null),
    training_organization_approval_number: Joi.string().allow(null),
    training_facility_location: Joi.string().allow(null),
    training_organization_quality_certifications: Joi.array().items(Joi.string()).allow(null),
    training_organization_contact_person: Joi.string().allow(null),
    training_organization_telephone: Joi.string().allow(null),
    training_organization_email: Joi.string().email().allow(null),
    applicant_name: Joi.string().allow(null),
    applicant_address: Joi.string().allow(null),
    applicant_date_of_birth: Joi.date().allow(null),
    applicant_email_address: Joi.string().email().allow(null),
    applicant_telephone_number: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line_number: Joi.string().allow(null),
    incidental_line_number: Joi.string().allow(null),
    high_school: Joi.object().allow(null),
    polytechnic: Joi.object().allow(null),
    university: Joi.object().allow(null),
    professional_qualification: Joi.object().allow(null),
    experience: Joi.object().allow(null),
    applicant_declaration_name: Joi.string().allow(null),
    applicant_declaration_date: Joi.date().allow(null),
    employer_responsible_charge_name: Joi.string().allow(null),
    employer_responsible_charge_date: Joi.date().allow(null),
    is_draft: Joi.boolean().default(false),
});

const trainingOrganizationFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    authorized_inspector: Joi.boolean().allow(null),
    design_engineer: Joi.boolean().allow(null),
    power_engineer: Joi.boolean().allow(null),
    welding_engineer: Joi.boolean().allow(null),
    refrigerator_engineer: Joi.boolean().allow(null),
    boiler_and_pressure_vessel_operator: Joi.boolean().allow(null),
    pressure_welder: Joi.boolean().allow(null),
    refrigeration_technician: Joi.boolean().allow(null),
    approved_person: Joi.boolean().allow(null),
    lift_technician: Joi.boolean().allow(null),
    crane_operator: Joi.boolean().allow(null),
    forklift_operator: Joi.boolean().allow(null),
    work_equipment_operator: Joi.boolean().allow(null),
    rigger: Joi.boolean().allow(null),
    scaffolding_technician: Joi.boolean().allow(null),
    abseiling_technician: Joi.boolean().allow(null),
    new_application: Joi.boolean().allow(null),
    re_application: Joi.boolean().allow(null),
    available_for_documentation_review: Joi.boolean().allow(null),
    exemption_request: Joi.boolean().allow(null),
    company_name: Joi.string().allow(null),
    physical_address: Joi.string().allow(null),
    year_of_commencing_business: Joi.string().allow(null),
    number_of_employee: Joi.number().integer().allow(null),
    member_nagobin: Joi.boolean().allow(null),
    member_leia: Joi.boolean().allow(null),
    member_indt: Joi.boolean().allow(null),
    member_other_bodies: Joi.string().allow(null),
    quality_certification: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line: Joi.string().allow(null),
    incidental_line: Joi.string().allow(null),
    contact_person: Joi.string().allow(null),
    telephone: Joi.string().allow(null),
    email_address: Joi.string().email().allow(null),
    technical_supervisor_name: Joi.string().allow(null),
    technical_supervisor_address: Joi.string().allow(null),
    technical_supervisor_email: Joi.string().email().allow(null),
    technical_supervisor_date_of_birth: Joi.date().allow(null),
    technical_supervisor_phonenumber: Joi.string().allow(null),
    high_school: Joi.object().allow(null),
    polytechnic: Joi.object().allow(null),
    university: Joi.object().allow(null),
    professional_qualification: Joi.object().allow(null),
    professional_qualification_institution: Joi.object().allow(null),
    experience: Joi.object().allow(null),
    name_of_user: Joi.string().allow(null),
    company_responsible_charge: Joi.string().allow(null),
    date_sign: Joi.date().allow(null),
    approval_category: Joi.string().allow(null),
    approval_class: Joi.string().allow(null),
    training_approval_number_ngtan: Joi.string().allow(null),
    director_of_factories: Joi.string().allow(null),
    date_sign_director_of_factories: Joi.date().allow(null),
    documents_uploaded: Joi.array().items(Joi.string()).allow(null),
    is_draft: Joi.boolean().default(false),
});

const renewalFormSchema = Joi.object({
    userId: Joi.number().integer().allow(null),
    date_received: Joi.date().allow(null),
    form_number: Joi.string().allow(null),
    form_type: Joi.string().allow(null),
    equipment_registration: Joi.boolean().allow(null),
    certificate_of_competence: Joi.boolean().allow(null),
    certificate_of_authorization: Joi.boolean().allow(null),
    documentation_available: Joi.boolean().allow(null),
    exemption_requested: Joi.boolean().allow(null),
    company_name: Joi.string().allow(null),
    company_address: Joi.string().allow(null),
    company_cac_registration_number: Joi.string().allow(null),
    year_of_commencement: Joi.string().allow(null),
    number_of_employees: Joi.number().integer().allow(null),
    nagobin_membership: Joi.boolean().allow(null),
    leia_membership: Joi.boolean().allow(null),
    other_memberships: Joi.array().items(Joi.string()).allow(null),
    quality_certifications: Joi.array().items(Joi.string()).allow(null),
    previous_authorization_certificate_number: Joi.string().allow(null),
    previous_authorization_date_of_issue: Joi.date().allow(null),
    previous_authorization_expiry_date: Joi.date().allow(null),
    renewal_reason: Joi.string().allow(null),
    competence_category: Joi.string().allow(null),
    competence_line_number: Joi.string().allow(null),
    incidental_line_number: Joi.string().allow(null),
    contact_person_name: Joi.string().allow(null),
    contact_person_email: Joi.string().email().allow(null),
    contact_person_phone: Joi.string().allow(null),
    responsible_charge_name: Joi.string().allow(null),
    declaration_date: Joi.date().allow(null),
    approval_category: Joi.string().allow(null),
    approval_class: Joi.string().allow(null),
    contractor_number: Joi.string().allow(null),
    director_of_factories: Joi.string().allow(null),
    director_signature_date: Joi.date().allow(null),
    uploaded_documents: Joi.array().items(Joi.string()).allow(null),
    is_draft: Joi.boolean().default(false),
});


module.exports = {
    authorizationApprovedSchema,
    authorizationManufacturerSchema,
    competencyCertificationFormSchema,
    trainingOrganizationFormSchema,
    renewalFormSchema
};